### ISSUE TITLE
Tests required when -DGEANT4_USE_USOLIDS="ALL" is enabled for Geant4.

### ISSUE THREAD

**Issue by david-rapagnani** [christopherpoole/CADMesh#11]
Hi,

when I try to run any work with CADMesh what I got is the following message

./cadmesh_example: error while loading shared libraries: libG4geomUSolids.so: cannot open shared object file: No such file or directory

I use geant4.10.03.p01 with USolids flag on during configuration (i.e. -DGEANT4_USE_USOLIDS="ALL") and got as message
GEANT4_USE_USOLIDS: Replacing all Geant4 solids with USolids equivalents (EXPERIMENTAL)
that should mean USolids is correctly implemented in Geant4. I could not find libG4geomUSolids.so anyway.

Any ideas?

Thanks,
David

**Comment by Bangjie** [comment]
Hello, I think you need compile [usolids library] (http://aidasoft.web.cern.ch/USolids), and add the lib or lib64 folder into your $LD_LIBRARY_PATH. I don't use usolid library but the descriptions above might solve your problems. Besides, I think it is not a 'cadmesh problem', because cadmesh library works well when I did not use USolids Library in cmake configurations in G4-10.3.1. I hope it may help you and good luck!
