### ISSUE TITLE
Improve the example documentation with regard to using tessellated and tetrahedral meshes.

### ISSUE THREAD

**Issue by stevenwalton** [christopherpoole/CADMesh#7]
I noticed a big difference between running
`./cadmesh_example ../macros/vis.mac ../../../models/cone.ply PLY`
and 
`./cadmesh_example ../macros/vis.mac ../../../models/cone.ply`
The first command outputs https://i.imgur.com/JV6NH3T.png
Whereas the second outputs https://i.imgur.com/TtqEt5q.png

I checked the cone file in FreeCAD and found that there was only one cone, the same happened with ParaView. I could not open with SolidWorks. 

I should also mention that I could not import an STL or PLY file from FreeCAD and I could not open an STL file from SolidWorks.

**Comment by christopherpoole** [comment]
This is expected behaviour given how the example works, see [here](https://github.com/christopherpoole/CADMesh/blob/master/examples/basic/src/DetectorConstruction.cc#L74); although this could be made more obvious in the documentation. For tetrahedral meshing to work the file type needs to be specified, so with this in mind, when the file type is specified, a tetrahedral mesh is generated and loaded as well as the tessellated mesh.

Regarding STL files from FreeCAD and SolidWorks, It could be that you are trying to load binary STL files which are currently not supported.

**Comment by christopherpoole** [comment]
See #8 for tracking improvements to the documentation regarding input file types.

**Comment by stevenwalton** [comment]
Thanks, I'll try ASCII formats out and see if they work as expected. The code is starting to become a lot more clear to me now.
